### ISSUE TITLE
Unable to deploy to Kapsule with a release greate than 0.0.9

### ISSUE THREAD

**Issue by cbernard-psee** [XenitAB/spegel#197]
Hi team, 
We are using Spegel on top of Scaleway Kapsule cluster. Behavior was great until we tried to upgrade from 0.0.9 to 0.0.11 or 0.0.12.
The upgrade failed, getting this error in registry container:
Search...
{"level":"error","ts":1694005879.5690522,"caller":"build/main.go:72","msg":"","error":"Containerd registry config path needs to be set for mirror configuration to take effect"

Since containerd settings can be managed by end users, any idea how to handle this ? Any possibilité to go back the the 0.0.9 behavior which was not facing such issue ? 
Thansk for your support

**Comment by phillebaba** [comment]
I added functionality to check that the Containerd configuration is set properly as it is otherwise cumbersome for end users to check. If you are getting this error it means that the mirror configuration path is either not set or different from the default configured in Spegel.

Do you know what it is set to in Kapsule?

**Comment by phillebaba** [comment]
Closing due to lack of response.
