### ISSUE TITLE
Add persistence

### ISSUE THREAD

**Issue by nbrns** [XenitAB/spegel#210]
Hi there,

Spegel sounds like a great project and we are interested in using it to avoid Docker Hub's rate limiting on Azure AKS which comes by the end of September.
During regular operations, we should not run into limits. However, we fear that this may happen in case of a disaster recovery. E.g. the whole cluster burns down and everything needs to be set up from scratch asap.

This would be another great use case for Spegel. However, if I got it right, Spegel does not provide a persistence layer. Is it possible to add persistence to Spegel such that a recovery via k8s level backup tools like Velero would be possible?

I hope that this might be a quick win simply by providing parts of the file system via a PV? Or is it all in-memory and there is no easy way to persist the local images?

All the best! Continue the great work.
Niklas

**Comment by phillebaba** [comment]
So the power of Spegel is that it piggybacks on top of the storage already used by Containerd as images pulled by Containerd are stored on the hosts disk. This reduces a lot of the complexity as all Spegel does is serve cached images. These images are stored for an undetermined amount of time and are only removed when the Kubernetes image garbage collector kicks in. By this definition Spegel is a best effort cache. However it is not really an issue for images used in the cluster, as the garbage collector cannot remove cached images for a running Pod. Which means that the biggest risk you face is that an image that has not been used for a long time is removed from all the nodes cache.

In your disaster scenario are you setting up a new cluster or just re-adding nodes to a cluster? A limitation of Spegel compared to running a dedicated private registry mirror is that bootstrapping from zero while external registries are down is not possible. The images have to exist on one of the nodes for the others to be able to pull the image.

Or are you worried about throttling caused by bursty image pulls during a disaster recovery? That case could in theory become a problem but it is heavily mitigated by Spegel. In a best case scenario an image is pulled once by a node from Docker Hub and then pulled from other nodes, though this may not occur if multiple replicas are started at the same time. You may face larger issues if you are pulling hundreds of different images from Docker Hub.

If I understood your use case what you are after is attaching a PVC to each Spegel instance where the images are stored. While this may be possible I think it would complicate the architecture of Spegel. We would also be in the territory of implementing an actual image registry in that case. If you have these concerns I think you would be better off using Spegel in conjunction with another "traditional" private registry mirror.

**Comment by phillebaba** [comment]
Closing this due to lack of response.
