### ISSUE TITLE
error retrieving resource lock system/spegel-leader-election

### ISSUE THREAD

**Issue by cbc02009** [XenitAB/spegel#339]
### Spegel version

v0.0.17

### Kubernetes distribution

Talos Linux

### Kubernetes version

v1.29.1

### CNI

Cilium

### Describe the bug

I am unable to get spegel working, and I can't seem to figure out what is going wrong. My pods keep crashing with the following error:
```
{"level":"error","ts":1707001260.0699086,"caller":"leaderelection/leaderelection.go:327","msg":"error retrieving resource lock system/spegel-leader-election: Get \"https://10.10.0.1:443/api/v1/namespaces/system/configmaps/spegel-leader-election\": dial tcp 10.10.0.1:443: i/o timeout\n","stacktrace":"k8s.io/client-go/tools/leaderelection.(*LeaderElector).tryAcquireOrRenew\n\t/go/pkg/mod/k8s.io/client-go@v0.27.4/tools/leaderelection/leaderelection.go:327\nk8s.io/client-go/tools/leaderelection.(*LeaderElector).acquire.func1\n\t/go/pkg/mod/k8s.io/client-go@v0.27.4/tools/leaderelection/leaderelection.go:247\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.27.4/pkg/util/wait/backoff.go:226\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.27.4/pkg/util/wait/backoff.go:227\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.27.4/pkg/util/wait/backoff.go:204\nk8s.io/client-go/tools/leaderelection.(*LeaderElector).acquire\n\t/go/pkg/mod/k8s.io/client-go@v0.27.4/tools/leaderelection/leaderelection.go:246\nk8s.io/client-go/tools/leaderelection.(*LeaderElector).Run\n\t/go/pkg/mod/k8s.io/client-go@v0.27.4/tools/leaderelection/leaderelection.go:203\nk8s.io/client-go/tools/leaderelection.RunOrDie\n\t/go/pkg/mod/k8s.io/client-go@v0.27.4/tools/leaderelection/leaderelection.go:223"}
```

I am using the helm chart with the following values: https://github.com/cbc02009/k8s-home-ops/blob/main/kubernetes/main/apps/system/spegel/app/helmrelease.yaml
```
    spegel:
      containerdSock: /run/containerd/containerd.sock
      containerdRegistryConfigPath: /etc/cri/conf.d/hosts
    service:
      registry:
        hostPort: 29999
    serviceMonitor:
      enabled: true
```

The config map mentioned in the error message doesn't exist in my deployment, which is likely why the api call is failing?

**Comment by phillebaba** [comment]
I setup a Talos cluster of my own to test things out, and I got things working using  your configuration for the registry config path. As you stated the API call is failing which is causing Spegel to crash. As a side not the reason Spegel needs to create a ConfigMap is because it needs to share its public ID for the p2p component to bootstrap.

I had a look at your other configuration and saw that you have defined a network policy. It does not look like the network policy allows outgoing traffic to the API server, which is why the leader election fails. Could you try adjusting the network policy and see if it works?

I will add Talos to the compatibility list for future users running Spegel on Talos.

**Comment by cbc02009** [comment]
@phillebaba Thanks for the response. The network policy was only added to see if it would make a difference after the issue was already observed. Oddly enough, removing the network policy now seems to have fixed the issue?

Anyway, thank you very much for your help.
